environment:
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"
    - nodejs_version: "7"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test